package frontend.DPSSModule;

/**
* DPSSModule/DPSSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DPSS.idl
* Wednesday, July 22, 2020 1:26:44 o'clock PM EDT
*/

public final class DPSSHolder implements org.omg.CORBA.portable.Streamable
{
  public DPSSModule.DPSS value = null;

  public DPSSHolder ()
  {
  }

  public DPSSHolder (DPSSModule.DPSS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DPSSModule.DPSSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DPSSModule.DPSSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DPSSModule.DPSSHelper.type ();
  }

}
