package replica3.DPSSModule;


/**
* DPSSModule/DPSS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DPSS.idl
* Wednesday, July 22, 2020 1:26:44 o'clock PM EDT
*/

public interface DPSS extends DPSSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface DPSS
