package frontend.FrontEndModule;


/**
* FrontEndModule/FrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Tuesday, July 28, 2020 12:30:14 o'clock PM EDT
*/

public interface FrontEnd extends FrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEnd
