package frontend.FrontEndModule;


/**
* FrontEndModule/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Tuesday, July 28, 2020 12:30:14 o'clock PM EDT
*/

public interface FrontEndOperations 
{
  String createPlayerAccount(String firstName, String lastName, String age, String userName, String password, String ipAddress);
  String playerSignIn(String userName, String password, String ipAddress);
  String playerSignOut(String userName, String ipAddress);
  String getPlayerStatus(String adminUsername, String adminPassword, String ipAddress);
  String transferAccount(String userName, String password, String oldIPAddress, String newIPAddress);
  String suspendAccount(String adminUsername, String adminPassword, String ipAddress, String usernameToSuspend);
  void shutdown();
} // interface FrontEndOperations
